apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: manifold-k8s-credentials-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "manifold-k8s-credentials-controller"
    spec:
      containers:
        - name: manifold-k8s-credentials-controller
          image: manifoldco/kubernetes-credentials:v0.0.4
          env:
            - name: K8S_NAMESPACE # required to talk to the Kubernetes API.
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MANIFOLD_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: manifold-secrets
                  key: api_token
            - name: MANIFOLD_TEAM
              valueFrom:
                secretKeyRef:
                  name: manifold-secrets
                  key: team
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
