apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: manifold:credentials
rules:
  - apiGroups: ["manifold.co"]
    resources: ["projects", "resources"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: manifold:credentials
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manifold:credentials
subjects:
  - name: manifold-credentials
    namespace: manifold-system
    kind: ServiceAccount
